apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mongo
  namespace: sa-p7
spec:
  schedule: "*/2 * * * *"  # Cada 2 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongo-script
              image: jsrmedina/cronjob-ms:latest
              env:
                - name: DATABASE_URL
                  value: "mongodb+srv://admin-sa:sacluster00@clustersa.at5ngtq.mongodb.net/cronjob_ms?retryWrites=true&w=majority&appName=ClusterSA"
          restartPolicy: OnFailure
